package com.upsellbackgroundactions

data class Names(
  val ACTION_STOP_SERVICE: String = "com.upsellbackgroundactions.ACTION_STOP_SERVICE",
  val ACTION_STOP_RESTART_SERVICE: String = "com.upsellbackgroundactions.ACTION_RESTART_SERVICE",
  val ACTION_START_RESTART: String = "com.upsellbackgroundactions.ACTION_START_RESTART",
  val ACTION_SHUTDOWN: String = "com.upsellbackgroundactions.ACTION_SHUTDOWN",
  val ACTION_RECOVERY: String = "com.upsellbackgroundactions.ACTION_RECOVERY",
  val SHARED_PREFERENCES_KEY: String = "com.upsellbackgroundactions.SHARED_PREFERENCES_KEY",
  val CHANNEL_ID: String = "RN_BACKGROUND_ACTIONS_CHANNEL",
  val CHANNEL_RESTART:String="UPSELL_BACKGROUND_ACTIONS_RESTART_CHANNEL",
  val CHANNEL_SHUTDOWN:String="UPSELL_BACKGROUND_ACTIONS_SHUTDOWN_CHANNEL",
  val CHANNEL_ONE_TIME_ID:String="UPSELL_BACKGROUND_ACTIONS_CHANNEL_ONE_TIME_ID",
  val CHANNEL_ONE_TIME:String="UPSELL_BACKGROUND_ACTIONS_CHANNEL_ONE_TIME",
  val SERVICE_NOTIFICATION_ID: Int = 92901,
  val SHUTDOWN_ONE_TIME_NOTIFICATION_ID:Int=100,
  val RECOVERY_ONE_TIME_NOTIFICATION_ID:Int=101,
  val PENDING_INTENT_RESTART_ALARM_REQUEST_CODE:Int=0,
  val PENDING_INTENT_SHUTDOWN_ALARM_REQUEST_CODE:Int=1,
  val PENDING_INTENT_RECOVERY_ALARM_REQUEST_CODE:Int =2,
  val PENDING_INTENT_SHUTDOWN_ONE_TIME_REQUEST_CODE:Int=3,
  val PENDING_INTENT_RECOVERY_ONE_TIME_REQUEST_CODE:Int=4,
  val PENDING_INTENT_RESTART_NOTIFICATION_REQUEST_CODE:Int=5,
  val PENDING_INTENT_SHUTDOWN_NOTIFICATION_REQUEST_CODE:Int=6,
  val PENDING_INTENT_RECOVERY_NOTIFICATION_REQUEST_CODE:Int =7,
  val PENDING_INTENT_AUTOPRINT_NOTIFICATION_REQUEST_CODE:Int =8,

  )
